sudo: required
dist: xenial

language: python
python:
  - "3.6"
  - "3.7"

env:
  global:
  - TEST_POOL="zpool"

cache:
  pip: true
  custom_install: true

before_install:
  - sudo scripts/travis/ubuntu/setup_zfs_requirements.sh
  - sudo scripts/travis/common/create_test_root.sh

branches:
  only:
    - /.*/ # Build all branches

install:
  - git clone https://github.com/johnramsden/zedenv.git
  - (cd zedenv && python setup.py install)
  - sudo env "PATH=$PATH" python setup.py install
  - sudo env "PATH=$PATH" pip install '.[test]'

script:
  - modinfo zfs | grep -iw version
  - modinfo spl | grep -iw version
  - sudo env "PATH=$PATH" pytest --pep8

